# Generated by Django 2.1.1 on 2018-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_imp',
            name='price',
            field=models.IntegerField(null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='order_new',
            name='price',
            field=models.IntegerField(null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='order_send',
            name='price',
            field=models.IntegerField(null=True, verbose_name='单价'),
        ),
    ]
