# Generated by Django 2.1.1 on 2018-09-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20180918_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imp',
            name='status',
            field=models.CharField(default='等待接单', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='order_new',
            name='status',
            field=models.CharField(default='等待接单', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='order_send',
            name='status',
            field=models.CharField(default='等待接单', max_length=20, verbose_name='状态'),
        ),
    ]
