# Generated by Django 2.1.1 on 2018-09-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20180919_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imp',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='order_new',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='order_send',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='时间'),
        ),
    ]
