# Generated by Django 2.1.1 on 2018-09-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_auto_20180919_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_send',
            name='price',
        ),
    ]
